### ISSUE TITLE
data-base-modelagem

### ISSUE THREAD

**Issue by rodrgojp99** [rodrgojp99/estante-virtual#2]

**Comment by fernandopassoss** [comment]
Modelagem feita! Assim que possível a implementação será feita utilizando o springboot.
[modelagem_completa.pdf](https://github.com/rodrgojp99/estante-virtual/files/14625734/modelagem_completa.pdf)

**Comment by fernandopassoss** [comment]
Correção: campo SENHA adicionado na tabela usuário.
[modelagem_completa.pdf](https://github.com/rodrgojp99/estante-virtual/files/14627615/modelagem_completa.pdf)

**Comment by fernandopassoss** [comment]
Correção: adição do campo **cpf_usuario** na tebela livro e remoção do campo **numero_cartao** da tabela usuario.
[modelagem_completa.pdf](https://github.com/rodrgojp99/estante-virtual/files/14628777/modelagem_completa.pdf)
